minor readme updates
deephaven/SuanShu pull request #4
Opened 2022-07-18 20:12 UTC by jakemulf

2022-07-18 20:13 UTC, jakemulf commented
I'm not sure what to put for some examples in here. I did find https://github.com/eugenp/tutorials/blob/master/libraries-data-2/src/main/java/com/baeldung/suanshu/SuanShuMath.java, is that applicable? If not can someone (@devinrsmith?) provide some examples?

2022-07-19 16:34 UTC, devinrsmith requested changes

2022-07-19 16:34 UTC, devinrsmith commented on README.md
> +<!-- https://mvnrepository.com/artifact/io.deephaven/SuanShu -->
No need for comment IMO.

2022-07-19 16:34 UTC, devinrsmith commented on README.md
> +// https://mvnrepository.com/artifact/io.deephaven/SuanShu
No need for comment IMO.

2022-07-19 16:34 UTC, devinrsmith commented on README.md
> +implementation group: 'io.deephaven', name: 'SuanShu', version: '0.1.0'
We should prefer the shorter form: `implementation 'io.deephaven:SuanShu:0.1.0'`

2022-07-19 18:40 UTC, jakemulf commented on README.md
> +
Updated to use search.maven

2022-07-19 18:40 UTC, jakemulf commented on README.md
> +<!-- https://mvnrepository.com/artifact/io.deephaven/SuanShu -->
Removed

2022-07-19 18:46 UTC, devinrsmith approved these changes

2022-07-19 20:28 UTC, chipkent requested changes

2022-07-19 20:28 UTC, chipkent commented on README.md
> +This extension fixes testcases and serialized the library.
```suggestion
SuanShu is a Java math library for numerical analysis, statistics, root finding, linear algebra, optimization, curve fitting, interpolation, regression, differential equation solvers, and more.  

This repository is a fork of the most recent Open Source SuanShu release (2012-06-06).  It has enhancements that include fixes to test cases, serialization, etc.  If you are interested in the commercially licensed version, see [https://nm.dev/](https://nm.dev/).
```

2022-07-19 20:32 UTC, merged